language: elixir
elixir:
  - 1.0.0
  - 1.0.1
  - 1.0.2
  - 1.0.3
sudo: false # to use faster container based build environment
otp_release:
  - 17.0
  - 17.1
  - 17.3
  - 17.4
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
services:
  - rabbitmq
